// Assembles index.html (the Vite entry) from the editable UI sources:
//   ui/amino-template.html  — the prototype's <x-dc> markup (visual + interaction spec)
//   ui/amino-app.js         — the Component, wired to the real matrix-events backend
// Run automatically via the `predev` / `prebuild` npm hooks. Edit the ui/* sources,
// never index.html directly (it is generated and overwritten).
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const component = fs.readFileSync(path.join(root, 'ui/amino-app.js'), 'utf8');

// The prototype's inline editors carry `autofocus="{{ true }}"`. The browser
// focuses the *static* <x-dc> copy at parse time; when dc-runtime later removes
// <x-dc>, that focused input blurs and its native onblur="{{ f.onCommit }}"
// runs in global scope (where `f` is undefined) → an uncaught ReferenceError at
// boot. dc-runtime still compiles autofocus on the live React copy, so stripping
// the static binding here is harmless and keeps boot clean.
const template = fs
  .readFileSync(path.join(root, 'ui/amino-template.html'), 'utf8')
  .replace(/\s*autofocus="\{\{[^}]*\}\}"/g, '');

if (component.includes('</script>')) {
  throw new Error('amino-app.js contains a literal </script> — would break inline embedding');
}

const html = `<!doctype html>
<!-- GENERATED by scripts/assemble-index.mjs from ui/amino-template.html + ui/amino-app.js. Do not edit. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>AMINO Immigration — RK Lacy Law</title>
<meta name="description" content="Encrypted case-management for RK Lacy Law — built on the matrix-events backend (no database, no API keys, end-to-end encrypted).">
<link rel="manifest" href="manifest.webmanifest">
<link rel="icon" href="icon.svg">
<link rel="stylesheet" href="airtable-sync-ui.css">
<meta name="theme-color" content="#faf9f5">
</head>
<body>
<x-dc>${template}</x-dc>
<script type="text/x-dc" data-dc-script>${component}</script>

<!-- ── AMINO Immigration ──────────────────────────────────────────────────────
     The handed-off prototype UX, wired to a real backend. There is no database,
     no API tier and no app-managed auth: rooms are tables, events are rows,
     fold(events) is the query, and a stock Matrix homeserver stores only
     end-to-end-encrypted ciphertext.
     Foundation: github.com/clovenbradshaw-ctrl/bare-metal-eo-matrix-app
     Ask-your-data engine (loaded lazily at runtime): github.com/clovenbradshaw-ctrl/eoreader3
-->
<!-- Foundation (Vite-built ESM): real Matrix homeserver — auth, E2EE, rooms, fold → window.MatrixLive -->
<script type="module" src="/src/main.js"></script>
<!-- Vendored React/ReactDOM so the design-component runtime needs no CDN -->
<script src="vendor/react.js"></script>
<script src="vendor/react-dom.js"></script>
<!-- Pure fold engine (window.MatrixEngine) + computed fields + Ask-your-data bridge -->
<script src="engine.js"></script>
<script src="formula.js"></script>
<!-- Materializes lazily-stored import set rows (window.AminoRows) so AMINO can
     project the data bare-metal imported (clients/cases/notes) into its CRM. -->
<script src="import-rows.js"></script>
<!-- The Database view's data engine (window.AminoDB): bare-metal's real
     buildTable / augmentState / listSets derivation, so the grid shows every
     imported set with real columns, rows, and relational links. -->
<script src="db-data.js"></script>
<!-- The query spine (window.AminoRowStore): a columnar per-set store with one
     query() — filter/sort/group/search/hide-fields/pagination — that views and
     the 1M-scale goal both ride on (docs/BUILD-PLAN.md, docs/SCALING.md). -->
<script src="row-store.js"></script>
<!-- Off-main-thread materializer (SCALING.md Phase 1): the pure parse+map
     (window.AminoMaterialize, also loaded inside rows.worker.js via
     importScripts) and its main-thread client (window.AminoRowsWorker) that
     feeds the row store without freezing the tab. The worker itself
     (rows.worker.js) is spawned at runtime, not script-included. -->
<script src="rows-materialize.js"></script>
<script src="rows-worker-client.js"></script>
<script src="data-chat.js"></script>
<!-- ── Airtable two-way sync (ported from the bare-metal foundation) ──────────
     Same engine, coordinator and import/schema modules as the foundation. The
     backend hooks they need (window.MatrixLive.importFile / shareAirtableToken /
     getSharedAirtableToken / getAirtableTokenInfo / revokeAirtableToken, and the
     _recordId/_deleted/import_seq shadow reconciliation in db-data.js) already
     exist in AMINO — these just light them up. -->
<script src="airtable-schema.js"></script>
<script src="airtable-sync.js"></script>
<script src="airtable-coordinator.js"></script>
<!-- Babel transforms the two JSX view modules into window.AirtableSchemaModal
     (the import dialog) and window.AirtableSyncPanel (the Sync-page surface),
     mounted into the dc-runtime tree via <x-import component-from-global-scope>. -->
<script src="vendor/babel.js"></script>
<script type="text/babel" data-presets="react" src="airtable-import.jsx"></script>
<script type="text/babel" data-presets="react" src="airtable-panel.jsx"></script>
<!-- Design-component runtime: binds the <x-dc> template to the Component view-model -->
<script src="dc-runtime.js"></script>
</body>
</html>
`;

fs.writeFileSync(path.join(root, 'index.html'), html);
console.log('assembled index.html (%d KB)', Math.round(html.length / 1024));
